import java.lang.Exception

fun main() {

    val number: Int? = null

    if (number != null) addOne(number)


}

fun addOne(n: Int) = println(n + 1)







